services:
    nginx: 
        image: nginx:1.19.10-alpine
        container_name: production_nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
            - 443:443

networks:
    default:
        external:
            name: int221-network
